### ISSUE TITLE
Support for nuproj extension

### ISSUE THREAD

**Issue by stefandevo** [bitrise-steplib/steps-xamarin-archive#11]
Hi

Since Xamarin.Studio 6.2 and latest VS2017 they have introduced a new project type: nuproj.
[More info 1](https://github.com/NuGet/NuGet.Build.Packaging)
[More info 2](https://github.com/NuGet/Home/wiki/NuGetizer-3000)
[More info 3](https://developer.xamarin.com/releases/studio/xamarin.studio_6.2/xamarin.studio_6.2/#NuGetizer_3000)

Currently this step is ignoring the extension and therefore giving an error upon building.
`failed to create xamarin builder, error: no project found with ID: EF64E3DC-84C3-426A-A4F4-2C3A1C03F67A` (where the guid is a sample)

It seems that [this line](https://github.com/bitrise-steplib/steps-xamarin-archive/blob/34cfd200a1d4b51a54011ee1972968253d5fa2a5/vendor/github.com/bitrise-tools/go-xamarin/analyzers/solution/solution.go#L93) is causing the failure.

Could you please add this so that we can use this step to compile this kind of projects as well?

**Comment by godrei** [comment]
Hi @stefandevo , 
thanks for the report!

nuproj seems to be a `library` type of project, but xamarin-archive step is expected to generate app archives, for ios ipa file, for android apk file,....
So the step should not care about this type of project files, i will update the step to omit them.

**Comment by godrei** [comment]
@stefandevo ,
thanks for the issue report!

It seems nuproj is used to generate NuGet packages, but xamarin-archive step is responsible to generate app archives (ipa file for ios, apk file for android, ...).

By the way this issue highlighted that we should update our go-xamarin (shared xamarin builder) package (used by every xamarin step).

I will manage to solve to care only about archivable project types and omit other project types.
