### ISSUE TITLE
Build fails when specifying multiple custom iOS options

### ISSUE THREAD

**Issue by alexshikov** [bitrise-steplib/steps-xamarin-archive#24]
When I specify a set of custom iOS options the error happens.

**Options to append to the iOS build command**
```
/p:DefineConstants="__IOS__;__MOBILE__;__UNIFIED__;STORE"
```

Error
```
MSBUILD : error MSB1006: Property is not valid.
Switch: __MOBILE__
```

**Comment by alexshikov** [comment]
Hm... a hint from this link actually helps https://confluence.atlassian.com/bamkb/property-is-not-valid-error-caused-by-auto-removal-of-quotes-from-msbuild-options-610435873.html

Options should be specified with wrapping double quote with single quotes:
```
/p:DefineConstants='"'__IOS__;__MOBILE__;__UNIFIED__;STORE'"'
```

**Comment by kdobmayer** [comment]
Thanks for the infos. I will close this issue, but if you need any help just let us know.

**Comment by alexshikov** [comment]
@kdobmayer I would recommend making a note in the step documetantion about this issue.

**Comment by viktorbenei** [comment]
@alexshikov can you please share a bit more info for reproduction / docs? We'd be happy to add this to the docs or even fix/improve if possible, but for that we'll have to be able to reproduce this. 

Also, did you try it without any `"` quotes? Given that this is a Go step it's probably not required to `"` quote guard the param (did you try `/p:DefineConstants=__IOS__;__MOBILE__;__UNIFIED__;STORE`?)
