### ISSUE TITLE
Build fails with /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2402,3): error : Could not find a part of the path '/platforms'.

### ISSUE THREAD

**Issue by erikwolfe02** [bitrise-steplib/steps-xamarin-archive#26]
Starting around May 21st, our Xamarin builds began failing on the xamarin-archive@1.5.0 step without any changes to the workflow . It looks like this might be related to the the NDK not being set for some reason. At the beginning of the step I see:

```
_ResolveMonoAndroidSdks:
  MonoAndroid Tools: /Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Xamarin/Android/
  Android Platform API level: 27
  TargetFrameworkVersion: v8.1
  Android NDK: /
  Android SDK: /Users/vagrant/Library/Developer/Xamarin/android-sdk-macosx/
  Android SDK Build Tools: /Users/vagrant/Library/Developer/Xamarin/android-sdk-macosx/build-tools/27.0.3/
  Java SDK: /usr/
```

And before these failures began, the NDK was:

`Android NDK: /Users/vagrant/Library/Developer/Xamarin/android-ndk/android-ndk-r15c/`

**Comment by godrei** [comment]
Hi, could you please attach your failed build URL?

**Comment by erikwolfe02** [comment]
Hi, sorry for the delay:
https://www.bitrise.io/build/833f6c9b091a69dd

**Comment by BirmacherAkos** [comment]
Hi!

It seems there was a strange issue with the Android NDK path on the Hybrid (Xamarin, Ionic...) stable stack.

We have manually fixed it. 
If you run a new build or just rebuild the failed build it should work now.
But if you still have the issue, you can change back to the Previous Hybrid (Xamarin, Ionic...) stack and try to run a new build.

**Comment by erikwolfe02** [comment]
Great! Thanks @godrei and @BirmacherAkos
