### ISSUE TITLE
Add build params configuration

### ISSUE THREAD

**Issue by RomaRudyak** [bitrise-steplib/steps-xamarin-archive#27]
Please add possibility to pass in additional build parameters.

**Comment by godrei** [comment]
Hi @RomaRudyak , the step has: `PLATFORM_build_command_custom_options` inputs, which you can use to pass additional parameters to the platform-specific build commands. Is not it fit your requirements?

**Comment by RomaRudyak** [comment]
@godrei thank you for the help it was the sing i searched for.
I thought that it was parameters for mtouch util
