### ISSUE TITLE
Step fails to find APK

### ISSUE THREAD

**Issue by sdebruyn** [bitrise-steplib/steps-xamarin-archive#29]
My builds fail because this step fails to find the APK.

```
    143 Warning(s)
    0 Error(s)
Time Elapsed 00:02:16.95
Switching to legacy exporter
Legacy exporter failed to find apk in ()
No output generated
```

I replaced the step with this script and that works without issues: `msbuild /t:$PROJECT_NAME:SignAndroidPackage /p:Configuration=$BITRISE_XAMARIN_CONFIGURATION $BITRISE_PROJECT_PATH`

Example: https://app.bitrise.io/build/fee7812d8a972a3d

**Comment by fehersanyi-bitrise** [comment]
Hello @SamuelDebruyn 

I searched the line "but no debug symbols file was found." on google and a few xamarin forum pop ups mentioned that enabling proGuard can fix this issue 🤔
for example this: https://forums.xamarin.com/discussion/132830/compiler-warning-directory-xxx-contains-yyy-dll-but-no-debug-symbols-file-was-found

**Comment by sdebruyn** [comment]
The "no debug symbols were found" is just a warning. The APK is still generated without issues. I ran this locally and found the APK in my bin folder, Bitrise just didn't pick it up.

**Comment by maukur** [comment]
I have same issue when i have custom build folder. 

For example : 
`Sandbox.Android\bin\AnyCPU\Custom-Debug` - not work 
`Sandbox.Android\bin\AnyCPU\Debug`  - work good

**Comment by bitce** [comment]
Hi @maukur  or @SamuelDebruyn,

In case this problem is persistent, can you guys send us a more recent build URL we could check the logs of? Thanks!
