### ISSUE TITLE
Support for App Bundles

### ISSUE THREAD

**Issue by heytherewill** [bitrise-steplib/steps-xamarin-archive#35]
Xamarin now supports [App Bundles](https://github.com/xamarin/xamarin-android/blob/master/Documentation/guides/app-bundles.md). We've changed our build system to generate a `.aab` rather than a `.apk` and then we started getting the following error on Bitrise in the archive step:

```
Legacy exporter failed to find apk in (/Users/vagrant/git/path)
No output generated
```

The weird part is that the `deploy to bitrise` step works normally and manages to find the `.aab` and attach it to the list of generated artifacts! The problem is simply that the Xamarin step is failing because it expects to find a  `.apk`.

Is using bundles not supported for Xamarin? If not, is it in the plans?

**Comment by Roland-Bak** [comment]
Hey there @heytherewill 👋

Thanks for bringing this to our attention!
Our Xamarin-related steps currently do not support App Bundles, but your request has been escalated to the Tooling Team, who will start working on updating this! 😉

**Comment by pdrj** [comment]
Hi @Roland-Bak, thanks for bringing this issue up to the Tooling Team. Are you able to say when can we expect the bundles support to be added?

**Comment by pdrj** [comment]
Hi @Roland-Bak, any updates on this? Thanks.

**Comment by dnoakes** [comment]
> Hey there @heytherewill 👋
> 
> Thanks for bringing this to our attention!
> Our Xamarin-related steps currently do not support App Bundles, but your request has been escalated to the Tooling Team, who will start working on updating this! 😉

Looking forward to this feature

**Comment by bitce** [comment]
Hi guys! There is no ETA we could provide for now as the team is swamped with tasks, but we'll make sure to notify you here once this is around the corner :)

**Comment by pdrj** [comment]
Thanks @bitce. Please let us know as soon as you have more info.

**Comment by lszucs** [comment]
Hey there @heytherewill!

Thanks for the PR! Can you please elaborate on how did you set this up on bitrise.io? Did you use a script step to build the `aab` file?

Based on the docs (https://docs.microsoft.com/en-us/xamarin/android/release-notes/9/9.4), exporting an actually deployable AAB has to be done using a command similar to this:

```
msbuild -restore AndroidApp.csproj ^
  -t:SignAndroidPackage ^
  -p:Configuration=Release ^
  -p:AndroidKeyStore=True ^
  -p:AndroidSigningKeyStore=com.contoso.keystore ^
  -p:AndroidSigningStorePass=password ^
  -p:AndroidSigningKeyAlias=keyAlias ^
  -p:AndroidSigningKeyPass=password
```



The reason I'm asking is, that we have the `PackageForAndroid` target hardcoded in the step, so currently, our expectation is, that this PR would not help with the `aab` export without modifying the related logic or introducing a new input. In fact, it wouldn't even output an `aab`.

Other than that, it looks good. 👌  We just need to make sure we know if there is anything else, that needs to be added, before release. :)

**Comment by mattmapadmi** [comment]
Any movement on this? It's been over a year since the last update.

**Comment by heytherewill** [comment]
@mattmapadmi You can use the fork I created for Toggl while bitrise doesn't merge the linked PR into into develop:

https://github.com/toggl/go-xamarin
https://github.com/toggl/steps-xamarin-archive

Simply use these steps instead of the default bitrise provided and things should work fine (as they have worked for us or over a year now)
