### ISSUE TITLE
Archive app extensions dSYM files

### ISSUE THREAD

**Issue by juanlaube** [bitrise-steplib/steps-xamarin-archive#37]
Are there any plans to include iOS app extensions dSYM files in the xamarin-archive step? Currently the only dSYM file included in the zip is for the host app.

We use AppCenter for our Xamarin app and it now supports app extensions, so we would like to start using this.

I checked the step source code and looks like it only picks for archive files with the pattern `*.app.dSYM`, however, app extensions use `*.appex.dSYM` thus ignoring those files for archive.

**Comment by juanlaube** [comment]
I should mention we would be happy to help if you are open to contributions 🙂

**Comment by bitce** [comment]
Hi @juanlaube!

Thanks for raising this :) We do not have any specific plans about this at the moment, but we are definitely open for contributions! We'd happy to see PRs open for existing steps too, as well as seeing [complete steps from the community](https://devcenter.bitrise.io/contributors/create-your-own-step/).
